apiVersion: v1
data:
  node.json: |
    [
        {
            "targets": [
                "192.168.0.159:9100"
            ],
            "labels": {
                "instance": "vm-192.168.0.159",
                "service": "node-service"
            }
        }

    ]
kind: ConfigMap
metadata:
  name: node-json
  namespace: zhangjt
